name: LoreBlockSaver
version: 1.1.0
main: de.dgamerworlds.LoreBlocks.LoreBlockSaver
api-version: 1.20
author: Dgamerworlds
description: Stores item lores and also appends them when the item is placed and mined.
commands:
  lore:
    description: Bearbeite die Lore eines Items
    usage: /lore add/remove/set/clear
  rename:
    description: Ändere den Namen eines Items
    usage: /rename <Text>
